# Generated by Django 5.2.7 on 2025-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', '収入'), ('EXPENSE', '支出'), ('INVESTMENT', '投資'), ('TRANSFER', '振替')], max_length=12),
        ),
    ]
