# Generated by Django 5.2.7 on 2025-11-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('fixed', '固定費'), ('variable', '変動費')], default='variable', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', '収入'), ('expense', '支出'), ('investment', '投資'), ('transfer', '振替')], max_length=12),
        ),
    ]
