# Generated by Django 5.2.7 on 2025-11-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_category_type_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('fixed', '固定費'), ('variable', '変動費'), ('investment', '投資')], default='variable', max_length=10),
        ),
    ]
